### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by Flamencoyster** [dckb-rescuer/v1-core#1]
Is it possible for me to get your rescue in the future if I bought the dckb on the secondary market?

**Comment by phroi** [comment]
Hello dear @Flamencoyster, I just noticed this issue, I'm soooo sorry!

As per original protocol, only the creator of the dCKB NervosDAO deposits can unlock them and there nothing that can be done about that.

That said in the future the dCKB Rescuer interface could add support selling these tokens at a fixed rate, so the original owners can get hold of them and current token owner can get their CKB value out. That said it's possible that this possibility is already offered by other platforms. Please refer to: https://talk.nervos.org/t/retrieving-staked-dckb-from-the-blockchain-as-the-website-nexisdao-com-closed-since-jan-2023/7841

Closing this issue, feel free to follow up in Nervos Talk!

Cheers, Phroi
